[project]
name = "rag-queue"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.136.3",
    "langchain-community>=0.4.2",
    "langchain-core>=1.4.0",
    "langchain-google-genai>=4.2.4",
    "langchain-huggingface>=1.2.2",
    "langchain-qdrant>=1.1.0",
    "load-dotenv>=0.1.0",
    "pypdf>=6.12.2",
    "rq>=2.9.0",
    "sentence-transformers>=5.5.1",
]
